# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

workspace 'ECPayPaymentGatewayKit-Example'

inhibit_all_warnings!
use_frameworks!

def podsIC
    
    pod 'ECPayPaymentGatewayKit', '1.8.1'
    
    #版本號自 1.5.0 起, SDK 僅支援 XCode15+。若仍使用 其他較低版本 XCode, 請往下參考其他安裝方式.
    # pod 'ECPayPaymentGatewayKit', :podspec => '/你的本地端路徑/ECPayPaymentGatewayKit.podspec'

    # 版本號 1.4.1_XCode15 請參考以下網址依步驟另行安裝
    # https://github.com/ECPay/ECPayPaymentGatewayKit_iOS/releases/tag/1.4.1_XCode15

    ##### Net #####
    pod 'PromiseKit' , '6.8.5'
    pod 'Alamofire', '5.10.1'
    ##### UI #####
    pod 'IQKeyboardManagerSwift', '7.0.0'
    ##### Data #####
    pod 'KeychainSwift', '16.0.1'
    pod 'SwiftyXMLParser', :git => 'https://github.com/yahoojapan/SwiftyXMLParser.git'
    pod 'CryptoSwift', '1.4.1'
end

target 'Example-Swift' do
  project 'Example-Swift/Example-Swift.xcodeproj'
  podsIC
end

static_frameworks = ['ECPayPaymentGatewayKit']
pre_install do |installer|
  installer.pod_targets.each do |pod|
    if static_frameworks.include?(pod.name)
      puts "#{pod.name} installed as static framework!"
      def pod.static_framework?;
        true
      end
    end
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        end
    end
end
