# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

workspace 'ECPayPaymentGatewayKit-Example'

inhibit_all_warnings!
use_frameworks!

def podsIC
    pod 'ECPayPaymentGatewayKit', '~> 1.0.1'
    ##### Net #####
    pod 'PromiseKit' , '~> 6.8.3'
    pod 'Alamofire', '~> 5.2.1'
    ##### UI #####
    pod 'IQKeyboardManagerSwift'
    ##### Data #####
    pod 'KeychainSwift', '~> 16.0'
    pod 'SwiftyJSON', '~> 4.2.0'
    pod 'SwiftyXMLParser', :git => 'https://github.com/yahoojapan/SwiftyXMLParser.git'
    pod 'CryptoSwift', '~> 0.14.0'
end

target 'Example-Swift' do
  project 'Example-Swift/Example-Swift.xcodeproj'
  podsIC
end
